"""Theme sweep: locate every object related to an arbitrary theme, across the whole world.

The driving scenario is real and external: a compliance pass, an IP review, a sudden
"remove everything about X by Friday". The content under inspection is mostly NOT
generated by this system (imported spreadsheets, distilled manuscripts, hand-written
entries), so the sweep cannot rely on any preset feature list or tag taxonomy. Recall is
layered instead:

  1. term layer    — the user's theme + their synonyms, matched lexically over EVERY
                     string field of EVERY object (fields are walked generically from the
                     serialized model, so new content types join the sweep for free);
  1.5 semantic layer — a real multilingual embedder (bge-m3) scores each not-yet-hit object
                     against the theme by cosine; a near-match is surfaced for review even when
                     it shares NO word with the theme (euphemism / paraphrase). This is the
                     "DFA + word embeddings" idea — a lexical word-list alone misses the
                     euphemisms a compliance pass exists to find. Deterministic, $0/local; it
                     self-disables on the hashing stub. The scores also order the capped judge.
  2. judge layer   — optionally, an LLM reads each not-yet-hit object and answers
                     "related to this theme?" with a reason and a quote (classification
                     with evidence, never generation);
  3. graph layer   — relations expand confirmed hits to their neighbours as
                     "review suggested" (a casino owner is suspect even if his own
                     description never mentions gambling).

The output is a work order for a HUMAN: every finding carries its evidence and the
report states exactly what was scanned and what was not (no silent sampling), because
the user of this feature must be able to say "we checked everything".
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any

import numpy as np

from ..content.models import ContentBundle
from ..llm.cache import Embedder
from ..llm.gateway import LLMGateway
from ..llm.jsonio import extract_json_object

_SNIPPET_CHARS = 90
_JUDGE_BATCH_SIZE = 10
_JUDGE_TEXT_CHARS = 320
_EMBED_TEXT_CHARS = 1200  # how much of an object's text the semantic layer embeds (speed cap)


def _is_semantic(embedder: Embedder | None) -> bool:
    """A real neural embedder (bge-m3) tags its model_id ``st:*``; the hashing stub does not.

    Reads ``model_id`` live so a runtime degrade (semantic model failed to load → hashing
    fallback) is seen as non-semantic — never snapshot this, or a degraded process would keep
    claiming ``st:`` (same live-read rule as ``VectorRetriever.is_semantic``)."""
    return embedder is not None and embedder.model_id.startswith("st:")


def _normalise_rows(matrix: np.ndarray) -> np.ndarray:
    """L2-normalise each row so a plain dot product is cosine similarity."""
    if matrix.size == 0:
        return matrix
    norms = np.linalg.norm(matrix, axis=1, keepdims=True)
    norms[norms == 0] = 1.0
    return matrix / norms


_JUDGE_SYSTEM_PROMPT = (
    "You are a content-compliance reviewer. You will receive a THEME and a numbered list "
    "of content objects (any genre, any language). For each object decide whether it is "
    "related to the theme — directly mentioning it, depicting it, or clearly evoking it. "
    "Judge only from the given text; do not guess beyond it. Return ONE JSON object, no "
    'markdown: {"judgements": [{"index": <number>, "related": true|false, '
    '"reason": "<short reason in the theme\'s language>", "quote": "<the exact phrase '
    'from the object that triggered the call, empty if unrelated>"}]} . '
    "Every listed object must appear exactly once in judgements."
)


@dataclass
class SweepFinding:
    ref: str
    name: str
    object_kind: str
    layer: str  # "term" | "semantic" | "judge" | "graph"
    evidence: str
    verdict: str  # "hit" | "review"


@dataclass
class SweepReport:
    theme: str
    terms: list[str]
    scanned_total: int
    scanned_by_kind: dict[str, int]
    findings: list[SweepFinding]
    llm_used: bool
    judged_count: int
    judge_skipped: int  # objects NOT shown to the judge (cap reached) — honesty counter
    semantic_used: bool = False  # whether the bge-m3 paraphrase layer ran (needs a real model)
    semantic_flagged: int = 0  # objects surfaced by meaning alone (no lexical hit)
    semantic_threshold: float = 0.0

    @property
    def hits(self) -> list[SweepFinding]:
        return [f for f in self.findings if f.verdict == "hit"]

    @property
    def review_suggested(self) -> list[SweepFinding]:
        return [f for f in self.findings if f.verdict == "review"]


def _string_leaves(value: Any, *, skip_keys: frozenset[str] = frozenset({"metadata"})) -> list[str]:
    """Collect every string leaf of a serialized model. Generic on purpose: the sweep
    must see ALL text a future content type carries, without anyone remembering to
    register its fields."""
    out: list[str] = []
    if isinstance(value, str):
        if value.strip():
            out.append(value)
    elif isinstance(value, dict):
        for key, item in value.items():
            if key in skip_keys:
                continue
            out.extend(_string_leaves(item, skip_keys=skip_keys))
    elif isinstance(value, list):
        for item in value:
            out.extend(_string_leaves(item, skip_keys=skip_keys))
    return out


def _corpus(bundle: ContentBundle) -> list[dict[str, Any]]:
    """Every world object as (ref, name, kind, text). Collections are enumerated from the
    bundle itself so nothing is silently left out of a sweep."""
    rows: list[dict[str, Any]] = []

    def add(kind: str, ref: str, name: str, payload: Any) -> None:
        dumped = payload.model_dump(mode="json")
        text = "\n".join(_string_leaves(dumped))
        rows.append({"ref": ref, "name": name, "kind": kind, "text": text})

    for entity_id, entity in bundle.entities.items():
        add("entity", f"entity:{entity_id}", entity.name, entity)
    for quest_id, quest in bundle.quests.items():
        add("quest", f"quest:{quest_id}", quest.title, quest)
    for region_id, region in bundle.regions.items():
        add("region", f"region:{region_id}", region.name, region)
    for poi_id, poi in bundle.pois.items():
        add("poi", f"poi:{poi_id}", poi.name, poi)
    for dlg_id, dialogue in bundle.dialogues.items():
        add("dialogue", f"dialogue:{dlg_id}", dlg_id, dialogue)
    for tree_id, tree in bundle.dialogue_trees.items():
        add("dialogue_tree", f"dialogue_tree:{tree_id}", tree.title or tree_id, tree)
    for term_id, term in bundle.terms.items():
        add("term", f"term:{term_id}", term.canonical, term)
    for text_id, localized in bundle.localized_texts.items():
        add("localized_text", f"localized_text:{text_id}", text_id, localized)
    for guide_id, guide in bundle.style_guides.items():
        add("style_guide", f"style_guide:{guide_id}", guide_id, guide)
    return rows


def _has_cjk(text: str) -> bool:
    return any("一" <= ch <= "鿿" for ch in text)


def _term_matches(term: str, text: str) -> bool:
    """Lexical membership of ``term`` in ``text``. CJK has no word boundaries, so it stays a
    substring test; a pure-Latin term uses ``\\b`` word boundaries so a compliance term like
    ``war`` does not false-hit ``warden`` / ``toward`` (same precision fix as S3's term rule)."""
    term = term.strip()
    if not term:
        return False
    if _has_cjk(term):
        return term.lower() in text.lower()
    return re.search(rf"\b{re.escape(term)}\b", text, re.IGNORECASE) is not None


def _snippet(text: str, term: str) -> str:
    lowered = text.lower()
    pos = lowered.find(term.lower())
    if pos < 0:
        return text[:_SNIPPET_CHARS]
    start = max(0, pos - _SNIPPET_CHARS // 3)
    end = min(len(text), pos + len(term) + _SNIPPET_CHARS)
    return (
        ("…" if start > 0 else "")
        + text[start:end].replace("\n", " ")
        + ("…" if end < len(text) else "")
    )


class ThemeSweepService:
    def __init__(
        self,
        *,
        bundle: ContentBundle,
        gateway: LLMGateway | None = None,
        embedder: Embedder | None = None,
    ) -> None:
        self.bundle = bundle
        self.gateway = gateway
        # A real semantic embedder (bge-m3) turns on the paraphrase layer; the hashing stub is
        # lexical, so it stays off to avoid surfacing char-overlap noise as "meaning".
        self.embedder = embedder if (embedder is not None and _is_semantic(embedder)) else None

    def sweep(
        self,
        theme: str,
        *,
        extra_terms: list[str] | None = None,
        use_llm: bool = False,
        max_judge: int = 400,
        semantic_threshold: float = 0.5,
        progress: Callable[[str, dict[str, Any]], None] | None = None,
    ) -> SweepReport:
        theme = theme.strip()
        if not theme:
            raise ValueError("清查主题不能为空。")
        terms = [theme] + [t.strip() for t in (extra_terms or []) if t.strip()]
        corpus = _corpus(self.bundle)
        findings: dict[str, SweepFinding] = {}

        # ---- layer 1: lexical, over every string field of every object
        for row in corpus:
            matched = [t for t in terms if _term_matches(t, row["text"])]
            if matched:
                findings[row["ref"]] = SweepFinding(
                    ref=row["ref"],
                    name=row["name"],
                    object_kind=row["kind"],
                    layer="term",
                    evidence=f"命中词「{matched[0]}」：{_snippet(row['text'], matched[0])}",
                    verdict="hit",
                )

        # ---- layer 1.5: semantic — catch paraphrase/euphemism the lexical layer cannot (the
        # "DFA + word embeddings" idea, with a multilingual model). Deterministic, $0/local. Each
        # unflagged object is scored against the terms by cosine; a near-match is surfaced for
        # review, and the scores order the (capped) LLM judge so its budget hits likeliest first.
        pending = [row for row in corpus if row["ref"] not in findings]
        semantic_scores = self._semantic_scores(terms, pending) if self.embedder else {}
        semantic_flagged = 0
        for row in pending:
            score = semantic_scores.get(row["ref"], 0.0)
            if score >= semantic_threshold:
                findings[row["ref"]] = SweepFinding(
                    ref=row["ref"],
                    name=row["name"],
                    object_kind=row["kind"],
                    layer="semantic",
                    evidence=f"语义相近（相似度 {score:.2f}）：{row['text'][:_SNIPPET_CHARS]}",
                    verdict="review",
                )
                semantic_flagged += 1
        # Re-read the embedder's backend live now that the semantic layer has embedded — a model
        # that degraded to hashing mid-run flips ``model_id`` to ``hashing-*``, so this reports the
        # backend actually used, not the construction-time guess (mirrors VectorRetriever).
        semantic_live = _is_semantic(self.embedder)

        # ---- layer 2: LLM judge on everything the lexical pass did not confirm, ordered by
        # semantic similarity so the cap is spent on the likeliest. A "related" verdict upgrades a
        # provisional semantic review to a confirmed hit with the model's reason.
        judged_count = 0
        judge_skipped = 0
        if use_llm and self.gateway is not None:
            judge_pool = sorted(
                pending, key=lambda r: (-semantic_scores.get(r["ref"], 0.0), r["ref"])
            )
            to_judge = judge_pool[:max_judge]
            judge_skipped = len(judge_pool) - len(to_judge)
            for start in range(0, len(to_judge), _JUDGE_BATCH_SIZE):
                batch = to_judge[start : start + _JUDGE_BATCH_SIZE]
                judged_count += len(batch)
                if progress is not None:
                    progress("judge", {"done": judged_count, "total": len(to_judge)})
                for index, reason, quote in self._judge_batch(theme, terms, batch):
                    row = batch[index]
                    evidence = f"模型判定：{reason}" + (f"（原文：{quote}）" if quote else "")
                    findings[row["ref"]] = SweepFinding(
                        ref=row["ref"],
                        name=row["name"],
                        object_kind=row["kind"],
                        layer="judge",
                        evidence=evidence,
                        verdict="hit",
                    )

        # ---- layer 3: graph neighbours of hits become "review suggested"
        hit_refs = {f.ref for f in findings.values() if f.verdict == "hit"}
        hit_ids = {ref.split(":", 1)[1] for ref in hit_refs}
        names = {row["ref"]: (row["name"], row["kind"]) for row in corpus}
        for relation in self.bundle.relations:
            for this_id, other_id in (
                (relation.source, relation.target),
                (relation.target, relation.source),
            ):
                if this_id not in hit_ids:
                    continue
                neighbour_ref = self._ref_of(other_id)
                if neighbour_ref is None or neighbour_ref in findings:
                    continue
                name, kind = names.get(neighbour_ref, (other_id, "entity"))
                findings[neighbour_ref] = SweepFinding(
                    ref=neighbour_ref,
                    name=name,
                    object_kind=kind,
                    layer="graph",
                    evidence=f"与命中对象 `{this_id}` 存在关系（{relation.kind}），建议人工复查。",
                    verdict="review",
                )

        by_kind: dict[str, int] = {}
        for row in corpus:
            by_kind[row["kind"]] = by_kind.get(row["kind"], 0) + 1
        ordered = sorted(
            findings.values(), key=lambda f: (f.verdict != "hit", f.object_kind, f.ref)
        )
        return SweepReport(
            theme=theme,
            terms=terms,
            scanned_total=len(corpus),
            scanned_by_kind=by_kind,
            findings=ordered,
            llm_used=bool(use_llm and self.gateway is not None),
            judged_count=judged_count,
            judge_skipped=judge_skipped,
            # Read the embedder's live backend AFTER the semantic layer has embedded: if the
            # model failed to load and degraded to the hashing stub mid-run, ``_is_semantic``
            # now reads ``hashing-*`` and reports False — never the construction-time snapshot,
            # so the work order can't claim "bge-m3 enabled" while running on the stub.
            semantic_used=semantic_live,
            semantic_flagged=semantic_flagged,
            semantic_threshold=semantic_threshold if semantic_live else 0.0,
        )

    def _semantic_scores(self, terms: list[str], rows: list[dict[str, Any]]) -> dict[str, float]:
        """Cosine of each object to its closest term, computed locally with the project embedder.

        Returns the max similarity over terms per object ref. Empty when there is nothing to score,
        so the lexical/judge layers are unaffected."""
        assert self.embedder is not None
        if not rows:
            return {}
        term_matrix = _normalise_rows(np.asarray(self.embedder.embed_many(terms), dtype=np.float32))
        object_matrix = _normalise_rows(
            np.asarray(
                self.embedder.embed_many([row["text"][:_EMBED_TEXT_CHARS] for row in rows]),
                dtype=np.float32,
            )
        )
        if term_matrix.size == 0 or object_matrix.size == 0:
            return {}
        # (objects × dim) @ (dim × terms) → (objects × terms); take each object's best term
        sims = object_matrix @ term_matrix.T
        best = sims.max(axis=1)
        return {row["ref"]: float(best[index]) for index, row in enumerate(rows)}

    def _ref_of(self, object_id: str) -> str | None:
        if object_id in self.bundle.entities:
            return f"entity:{object_id}"
        if object_id in self.bundle.quests:
            return f"quest:{object_id}"
        if object_id in self.bundle.pois:
            return f"poi:{object_id}"
        if object_id in self.bundle.regions:
            return f"region:{object_id}"
        if object_id in self.bundle.dialogue_trees:
            return f"dialogue_tree:{object_id}"
        return None

    def _judge_batch(
        self, theme: str, terms: list[str], batch: list[dict[str, Any]]
    ) -> list[tuple[int, str, str]]:
        # one object = one numbered line: embedded newlines would detach an object's text
        # from its index and corrupt the judgement mapping
        listing = "\n".join(
            f"{index}. [{row['kind']}] {row['name']}："
            + row["text"][:_JUDGE_TEXT_CHARS].replace("\n", " ")
            for index, row in enumerate(batch)
        )
        synonyms = "、".join(terms[1:]) if len(terms) > 1 else ""
        user = (
            f"THEME：{theme}"
            + (f"（关联词：{synonyms}）" if synonyms else "")
            + f"\n\nOBJECTS:\n{listing}"
        )
        raw = self.gateway.complete(  # type: ignore[union-attr]
            task="theme_sweep", system=_JUDGE_SYSTEM_PROMPT, user=user
        )
        results: list[tuple[int, str, str]] = []
        try:
            # shared balanced-brace extractor (tolerates fences/prose), same as every other LLM
            # parse site — round 31's jsonio dedup had missed the sweep judge.
            payload = extract_json_object(raw)
        except ValueError:
            return results  # one bad batch must not sink the sweep; coverage stays in stats
        for item in payload.get("judgements") or []:
            if not isinstance(item, dict) or not item.get("related"):
                continue
            try:
                index = int(item.get("index", -1))
            except (TypeError, ValueError):
                continue
            if 0 <= index < len(batch):
                results.append(
                    (index, str(item.get("reason") or "相关"), str(item.get("quote") or ""))
                )
        return results


class OfflineSweepJudgeProvider:
    """Deterministic judge double. It relates an object when any single CJK character of
    the theme appears in the object text — deliberately LOOSER than the term layer's
    whole-phrase match, so tests can observe the judge catching rephrased content the
    lexical pass missed (the real judge's whole job). $0, no network."""

    def complete(self, *, system: str, user: str, model: str) -> tuple[str, int, int]:
        theme_line = user.split("\n", 1)[0]
        theme = theme_line.replace("THEME：", "").split("（", 1)[0].strip()
        theme_chars = [ch for ch in theme if not ch.isascii()]
        judgements = []
        for line in user.splitlines():
            stripped = line.strip()
            if not stripped or not stripped[0].isdigit() or "." not in stripped:
                continue
            index_text, _, body = stripped.partition(".")
            matched = next((ch for ch in theme_chars if ch in body), None)
            judgements.append(
                {
                    "index": int(index_text),
                    "related": matched is not None,
                    "reason": f"涉及主题要素「{matched}」" if matched else "",
                    "quote": matched or "",
                }
            )
        return json.dumps({"judgements": judgements}, ensure_ascii=False), 30, 20


def render_sweep_markdown(report: SweepReport) -> str:
    """The work order, as a portable checklist the team can tick off anywhere."""
    lines = [
        f"# 专项清查工作单：{report.theme}",
        "",
        f"- 检索词：{'、'.join(report.terms)}",
        f"- 扫描范围：全库 {report.scanned_total} 个对象（"
        + "，".join(f"{kind} {count}" for kind, count in sorted(report.scanned_by_kind.items()))
        + "）",
        "- 语义近似（向量）："
        + (
            f"已启用（bge-m3，阈值 {report.semantic_threshold:.2f}），按义召回 "
            f"{report.semantic_flagged} 个待查"
            if report.semantic_used
            else "未启用（需安装语义模型；当前仅词面）"
        ),
        "- 语义判定（模型逐项）："
        + (
            f"已启用，逐项判定 {report.judged_count} 个"
            if report.llm_used
            else "未启用（仅词面命中 + 关系扩散）"
        )
        + (
            f"；**有 {report.judge_skipped} 个对象未判定（超出上限）**"
            if report.judge_skipped
            else ""
        ),
        f"- 结论：直接命中 {len(report.hits)}，关联待查 {len(report.review_suggested)}",
        "",
        "## 直接命中（需处理）",
        "",
    ]
    if report.hits:
        for finding in report.hits:
            lines.append(f"- [ ] `{finding.ref}` **{finding.name}** — {finding.evidence}")
    else:
        lines.append("（无）")
    lines += ["", "## 关联对象（建议复查）", ""]
    if report.review_suggested:
        for finding in report.review_suggested:
            lines.append(f"- [ ] `{finding.ref}` **{finding.name}** — {finding.evidence}")
    else:
        lines.append("（无）")
    return "\n".join(lines) + "\n"
